title: Sound Bytes
description: A coding competition
theme: jekyll-theme-midnight
url: https://coding-competitions.github.io/sound-bytes
collections:
  examples:
    output: true
    lang: true
    len: true